name: Synchronize Pointag

on:
  delete:

  push:
    tags:
      - '**'

jobs:
  synchronize-pointag:
    permissions:
      contents: write
    uses: Arthri/synchronize-pointag/.github/workflows/i.yml@v2
